source 'http://rubygems.org'

gem 'rails'
gem 'sqlite3', '~> 1.3.9', platform: :ruby
gem 'jruby-jars', '1.7.15', platform: :jruby
gem 'jdbc-sqlite3', '~> 3.8', platform: :jruby
gem 'activerecord-jdbc-adapter', '~>1.3', platform: :jruby
gem 'activerecord-jdbcsqlite3-adapter', '~>1.3', platform: :jruby
gem 'jruby-openssl', '~>0.9', platform: :jruby
gem 'activerecord' , '~>4.1', '<4.2'
gem 'jquery-rails'
gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'

group :development, :test do
  gem 'rake'
  gem 'spring'
  gem 'rspec-core', '~> 3.0', '< 3.2'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'poltergeist'
  gem 'faker'
  gem 'fabrication', '~> 2.2.2s'
  gem 'guard'
  gem 'guard-rspec'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
  gem 'ci_reporter'
  gem 'ci_reporter_rspec'
end
